// #######################################################################
// NOTICE
//
// This software (or technical data) was produced for the U.S. Government
// under contract, and is subject to the Rights in Data-General Clause
// 52.227-14, Alt. IV (DEC 2007).
//
// Copyright 2019 The MITRE Corporation. All Rights Reserved.
// #######################################################################

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mitre_biqt_BIQT */

#ifndef _Included_org_mitre_biqt_BIQT
#define _Included_org_mitre_biqt_BIQT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mitre_biqt_BIQT
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mitre_biqt_BIQT_initialize(JNIEnv *,
                                                                    jobject);

/*
 * Class:     org_mitre_biqt_BIQT
 * Method:    getProviders
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL
Java_org_mitre_biqt_BIQT_getProviders(JNIEnv *env, jobject biqt);

/*
 * Class:     org_mitre_biqt_BIQT
 * Method:    runProvider
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mitre_biqt_BIQT_runProvider(
    JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_mitre_biqt_BIQT
 * Method:    runModality
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mitre_biqt_BIQT_runModality(
    JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_mitre_biqt_BIQT
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mitre_biqt_BIQT_cleanup(JNIEnv *,
                                                                 jobject);

#ifdef __cplusplus
}
#endif
#endif
